Module2 task2
htmlacademy-php/1604803-readme-12 pull request #4
Opened 2021-02-18 10:48 UTC by OlegSail

Данил, добрый день! Направляю на проверку 2-е задание 2-го модуля.

2021-02-19 07:10 UTC, pyatnitsev requested changes

2021-02-19 07:10 UTC, pyatnitsev commented on index.php
> +    //'content' => 'Не могу дождаться начала финального сезона своего любимого сериала!',
почему закомментировано?

2021-02-19 07:10 UTC, pyatnitsev commented on index.php
> +function cut_text ($text, $num_letters = 300) {
тут можно типы данных добавить string $text, int $num_letters = 300

2021-02-19 07:10 UTC, pyatnitsev commented on index.php
> +    $str_count = 0;                     // общая длина строки
ну по смыслу - str_length :)

2021-02-19 07:10 UTC, pyatnitsev commented on index.php
> +        $str_count = $str_count + $val_count;
Можно короче - $str_count += $val_count;

2021-02-19 07:10 UTC, pyatnitsev commented on index.php
> +    if ($str_count < $num_letters) {
Лучше разделять - пусть функция возвращает значение, вместо вывода на страницу.
Вот это важно и нужно исправить.

2021-02-19 07:10 UTC, pyatnitsev commented on index.php
> +                        cut_text ($value['content']);   // добавляем функцию ограничивающую длину текста
а вот тут уже тогда echo  cut_text($value['content']);

2021-02-19 11:37 UTC, OlegSail commented on index.php
> +    //'content' => 'Не могу дождаться начала финального сезона своего любимого сериала!',
Просто добавил длинный текст, чтобы показать, что функция работает. Все вернул обратно.

2021-02-19 11:37 UTC, OlegSail commented on index.php
> +function cut_text ($text, $num_letters = 300) {
Исправил.

2021-02-19 11:37 UTC, OlegSail commented on index.php
> +    $str_count = 0;                     // общая длина строки
Согласен)). Поправил.

2021-02-19 11:38 UTC, OlegSail commented on index.php
> +        $str_count = $str_count + $val_count;
Исправил.

2021-02-19 11:38 UTC, OlegSail commented on index.php
> +    if ($str_count < $num_letters) {
У меня была такая мысль, но я не понимал как это сделать.

2021-02-19 11:40 UTC, OlegSail commented on index.php
> +                        cut_text ($value['content']);   // добавляем функцию ограничивающую длину текста
Сделал через возврат от функции массива с проверочной переменной  $flag. Не знаю насколько это правильное решение, но ничего лучше придумать не смог.

2021-02-23 19:26 UTC, pyatnitsev commented on index.php
> +                        cut_text ($value['content']);   // добавляем функцию ограничивающую длину текста
Не пойдет, предлагаю обсудить.

2021-02-25 18:46 UTC, pyatnitsev approved these changes

2021-02-25 18:46 UTC, merged